namespace Datacute.AdditionalTextConstantGenerator
{
    internal static class Templates
    {
        private const string GeneratorNamespace = "Datacute.AdditionalTextConstantGenerator";
        private const string AttributeName = "AdditionalTextConstantsAttribute";
        public const string AttributeFullyQualified = GeneratorNamespace + "." + AttributeName;

        public const string AttributeClass = /* language=c# */
            @"
namespace Datacute.AdditionalTextConstantGenerator
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
    internal sealed class AdditionalTextConstantsAttribute : global::System.Attribute
    {
        /// <summary>
        /// Use a source generator to add string constants to this class for each AdditionalText file 
        /// found in the specified <see cref=""Path"">path</see>,
        /// and where the file name's <see cref=""Extension"">extension</see> matches the given extension.
        /// </summary>
        /// <param name=""extension"">The file name extension to include</param>
        /// <param name=""path"">The folder path to include</param>
        public AdditionalTextConstantsAttribute(string extension, string path)
        {
        }
    }
}";
        
        public const string AutoGeneratedComment = /* language=c# */
            @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Datacute.AdditionalTextConstantGenerator.
// </auto-generated>
//------------------------------------------------------------------------------";

        public const string ClassDocComments = /* language=c# */
            @"/// <summary>
/// This class's string constants are generated from project files meeting the criteria:
/// <list type=""bullet"">
/// <item>
/// <description>they are an <c>AdditionalFile</c></description>
/// </item>
/// <item>
/// <description>they are in the project folder <c>{0}</c></description>
/// </item>
/// <item>
/// <description>they have the extension <c>{1}</c></description>
/// </item>
/// </list>
/// </summary>
/// <remarks>
/// {2}
/// </remarks>
";

        public const string StringConstantDocCommentTemplate = /* language=c# */
            @"
/// <summary>Text value of the Additional Text: {0}</summary>
/// <value>
/// <code>{1}
/// </code>
/// </value>
";

        public const string StringConstantTemplate = /* language=c# */
            @"public const string {0} = @""{1}"";";

        public const string DesignTimeStringConstantTemplate = /* language=c# */
            @"public const string {0} => ""Design Time"";";
    }
}